### ISSUE TITLE
Where is the video ?

### ISSUE THREAD

**Issue by habeeeb4u** [xueqian-chen/SciDownl-AutoCaptcha#1]

**Comment by xueqian-chen** [comment]
I'm sorry, I haven't upload the video. In fact, I recorded a video but the audio was bad. I will record a new one and upload it as soon as possible.

**Comment by habeeeb4u** [comment]
can u guide me how to install this package ? i tried scidownl.

**Comment by xueqian-chen** [comment]
> 
> 
> can u guide me how to install this package ? i tried scidownl.

I will upload the video in 12 hours. It is a little complicated because a commercial captcha identification system is need. And there is only Chinese [website](http://www.chaojiying.com) for this captcha identification system. That's why I introduce it using video.

**Comment by xueqian-chen** [comment]
Hi, habeeeb4u. I have upload [tutorial.md](https://github.com/xueqian-chen/SciDownl-AutoCaptcha/blob/master/tutorial.md). Now you can find the detailed instructions.

**Comment by habeeeb4u** [comment]
Thank You !
